spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379
    rest:
      base-path: http://localhost:8080/

jwt:
  secret: 236979CB6F1AD6B6A6184A31E6BE37DB3818CC36871E26235DD67DCFE4041492



#MyBatis -> mybatis-config.xml works
mybatis:
  config-location: classpath:mybatis-config.xml
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.example.insiderback.member.model, com.example.insiderback.common.mybatis
#  type-handlers-package: com.example.insider-back.common.mybatis
logging:
  level:
    com:
      example:
        insiderback:
          member:
            repository: trace

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
#        exclude: "env,beans"
  endpoint:
    shutdown:
      enabled: true
  health:
    show-details: always
